export const SEARCH_ITEM = "SEARCH_ITEM"
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM"
export const UPDATE_SOCKET = "UPDATE_SOCKET"
export const TOGGLE_NEW_DATA_ALERT = "TOGGLE_NEW_DATA_ALERT"

